# Generated by Django 4.2.5 on 2023-11-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blogpost_publish_date_blogpost_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
